[package]
edition = "2018"
name = "hedgewars-server"
version = "0.0.1"
authors = [ "Andrey Korotaev <a.korotaev@hedgewars.org>" ]

[features]
official-server = ["openssl", "mysql"]
tls-connections = ["openssl"]
default = []

[dependencies]
getopts = "0.2"
rand = "0.8"
chrono = "0.4"
mio = { version = "0.7", features = ["os-poll", "net"] }
slab = "0.4"
netbuf = "0.4"
nom = "5.1"
env_logger = "0.8"
log = "0.4"
base64 = "0.13"
bitflags = "1.1"
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
openssl = { version = "0.10", optional = true }
mysql = { version = "15.0", optional = true }

[dev-dependencies]
proptest = "0.9"
