[package]
name = "hedgewars-network-protocol"
version = "0.1.0"
authors = ["Andrey Korotaev <a.korotaev@hedgewars.org>"]
edition = "2018"

[dependencies]
nom = "6"
serde_derive = "1.0"
serde = "1.0"

proptest = "1.0"